### ISSUE TITLE
不支持FORGE使用

### ISSUE THREAD

**Issue by aimarxjg** [thisjam/sd-webui-oldsix-prompt#40]
在里面装了几次都不行，直接报错
[sd-webui-freeu] Controlnet support: *enabled*
*** Error loading script: old_six_prompt.py
    Traceback (most recent call last):
      File "F:\webui_forge_cu121_torch21\webui\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "F:\webui_forge_cu121_torch21\webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "F:\webui_forge_cu121_torch21\webui\extensions\sd-webui-oldsix-prompt\scripts\old_six_prompt.py", line 6, in <module>
        from bs4 import BeautifulSoup
    ModuleNotFoundError: No module named 'bs4'

**Comment by LiJieqin** [comment]
我也遇到相同的问题，请问你解决了吗

**Comment by aimarxjg** [comment]
> 我也遇到了相同的问题，请问您解决了吗

没有，他们推荐装类似的ONE PROMPT 那个插件 ，但是那个插件我用起来不顺手，还有点卡顿，没老6爽快

**Comment by LiJieqin** [comment]
我明明已经安装了bs4,但是它就是报错说找不到这个模块

**Comment by LiJieqin** [comment]
我解决这个问题了  它找不到这个模块是因为stable-diffusion-webui没有bs4，你把你装的那个bs4的包放到你的stable-diffusion-webui目录下面就可以了

**Comment by aimarxjg** [comment]
> 我解决这个问题了它找不到这个模块是因为stable-diffusion-webui没有bs4，你把你装的那个bs4的包放到你的stable-diffusion-webui目录下面就可以了

啊 还是你厉害~，BS4文件是哪一个呀？你是说把秋叶包里面的BS4文件包放到FORGE文件夹下面就可以吗

**Comment by LiJieqin** [comment]
就把bs4这个文件夹放到跟你的extensions文件夹同级目录就行了

**Comment by aimarxjg** [comment]
> 把bs4这个文件夹装载的extensions文件夹同级目录就行了
谢谢你，已经可以用了😁

**Comment by LiJieqin** [comment]
不客气哦，以后有问题可以相互讨论哈哈

**Comment by ecgke** [comment]
请问这个bs4在哪下载？

**Comment by aimarxjg** [comment]
> 请问这个bs4在哪里下载？

就在秋叶包里面 直接搜，复制到敏神包同位置

**Comment by LiJieqin** [comment]
你可以直接pip install bs4，一般在你装python的Lib/site-packege下面

**Comment by ecgke** [comment]
感谢两位兄弟
