### ISSUE TITLE
無法載入old_six_prompt

### ISSUE THREAD

**Issue by chao0707** [thisjam/sd-webui-oldsix-prompt#42]
啟動時得到以下錯誤，請幫我看看。
我試著自己裝beautifulsoup，但我對python的虛擬環境不熟。

*** Error loading script: old_six_prompt.py
    Traceback (most recent call last):
      File "D:\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\stable-diffusion-webui\extensions\sd-webui-oldsix-prompt\scripts\old_six_prompt.py", line 6, in <module>
        from bs4 import BeautifulSoup
    ModuleNotFoundError: No module named 'bs4'

**Comment by nbet** [comment]
me too~

**Comment by reziozhou** [comment]
get the same error

**Comment by Richard574** [comment]
how to fix it ? I try to install beautifusoup4 package, dosn't work .

**Comment by Richard574** [comment]
> how to fix it ? I try to install beautifusoup4 package, doesn't work .

Solved this problem follow the steps as below :
![image](https://github.com/thisjam/sd-webui-oldsix-prompt/assets/32863147/70f339e9-338f-4723-87c5-487a05e8001d)
according to the console error message, it is inferred that it is due to there is no beautifulsoup packages.
step1: INTO directoy folder **XXXX:\XXXX\stable-diffusion-webui\venv\Scripts** 
step2: RUN  pip install beautifulsoup4 . then **RESTART** webui.bat. 
step3: CHECK the console, there is no error "ModuleNotFoundError: No module named 'bs4'"
hope can help you.
