### ISSUE TITLE
加载时报*** Error loading script: old_six_prompt.py 怎么解决？

### ISSUE THREAD

**Issue by mohand505** [thisjam/sd-webui-oldsix-prompt#46]
*** Error loading script: old_six_prompt.py
    Traceback (most recent call last):
      File "/Users/junxu/stable-diffusion-webui/modules/scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "/Users/junxu/stable-diffusion-webui/modules/script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/Users/junxu/stable-diffusion-webui/extensions/sd-webui-oldsix-prompt-main/scripts/old_six_prompt.py", line 6, in <module>
        from bs4 import BeautifulSoup
    ModuleNotFoundError: No module named 'bs4'

**Comment by lalala-233** [comment]
你需要安装 bs4，这个很迷……

我是 Linux 用户，使用 `./webui.sh`

输入 `./venv/bin/pip install bs4` 安装 bs4 即可。
